translations = {"zh_TW": {"已开启": "已開啟","已关闭": "已關閉","On": "已開啟","Off": "已關閉"},
                "zh_CN": {"On": "已开启","Off":"已关闭","已開啟":"已开启","已關閉":"已关闭","嗎":"吗","項":"项","掃":"扫","鑰":"钥",
                          "軟體":"软件","確定":"确认","檔案":"文件","當":"当","權限":"权限","惡意":"恶意","設定":"设置","後":"后",
                          "關於":"关于","護":"护","引導扇區":"引导扇区","錯誤":"错误","實時":"实时","復":"复","攔":"拦","請":"请",
                          "統":"统","刪":"删","發現":"发现","進":"进","個":"个","選":"选","啟":"启","監":"监","並":"并","本機":"电脑",
                          "資料":"数据","日誌":"日志","靈":"灵","這":"这","會":"会","誤殺":"误杀","題":"题","澤":"泽","語":"语",
                          "裝":"装","徑":"径","盤":"盘","隱":"隐","開發":"开发","動":"动","關閉":"关闭","資訊":"资讯","總數":"总数",
                          "訂":"订","稱":"称","類":"类","輸":"输","執":"执","數":"数","尋":"寻","變":"变","戶":"户","碼":"码",
                          "網":"网","詢":"询","製":"制","測試":"测试","員":"员","許":"许","條":"条","藍":"蓝","紅":"红","綠":"绿",
                          "態":"态","擇":"择","態":"态","態":"态","態":"态","態":"态","態":"态",},
                "en_US": {"On":"On","Off":"Off","已開啟":"On","已關閉":"Off","已开启":"On","已关闭":"Off","系統":"System ",
                          "啟用":"Enable ","停用":"Disable ","創建":"Create ","日期":"Date ","重啟":"Reboot ","嗎":"","檔案":"File ",
                          "存取被拒":"Access denied ","病毒":"Virus ","個":"","選擇":"Select ","的":"","方式":"Method ","需要":"Need ",
                          "正在掃描":"Scanning ","正在刪除":"Deleting ","正在尋找":"Searching ","失敗":"Failed ","請":"Please ",
                          "當前":"Currently ","未":"Not ","防護":"Protect ","裝置":"Device ","這部":"This ","發現":"Found ","，":", ",
                          "找到":"Find ","受到":"Been ","密鑰錯誤":"Key Error","錯誤":"Error ","修復":"Repair ","完成":"Complete ",
                          "正在初始化中":"Initializing ","實時":"Real-Time ","到":"For ","您確定":"Are You Sure You ","狀態":"State",
                          "成功":"Success ","清理":"Cleanup ","執行":"Execute ","警告":"Warning ","輸入了":"Input ","刪除":"Delete ",
                          "搜尋":"Search ","此":"This ","要":"Want To ","安全模式":"Safe Mode","您":"You ","不安全":"Unsafe","已":"Has ",
                          "命令":"Command","不是有效":"Is Not A Valid ","修改":"Modify ","用戶":"User ","使用":"Use ","哈希":"Hash",
                          "重置":"Reset ","網路":"Network ","配置":"Config ","是":"Is ","選項":"Options ","監控":"Monitor ","確定":"OK",
                          "進程":"Process ","可以":"To ","中":"","並":"And ","攔截":"Block ","引導扇區":"Boot Sector ","工具":"Tools",
                          "掃描":"Scan ","設定":"Setting","關於":"About","靈敏度":"Sensitivity ","提高":"Improve ","高":"High ",
                          "模式":"Mode ","但":"But ","這也可能會造成誤殺":"It Can Also Cause Manslaughter ","安全":"Security ","指令":"",
                          "白色主題":"White","黑色主題":"Black","黃色主題":"Yellow","藍色主題":"Blue","紅色主題":"Red","綠色主題":"Green",
                          "顯色":"Color ","主題":"Themes ","語言":"Language ","製作":"Make","介面":"GUI ","核心":"Core ","路徑":"Path ",
                          "測試人員":"Testers","官方網站":"Website","許可條款":"License Terms","全盤":"Full ","隱私":"Privacy ",
                          "開發":"Devs ","更多":"More ","管理":"Manage","垃圾":"File ","啟動":"Enable ","關閉":"Disabled ","輸出":"Output",
                          "版本資訊":"Information","私密":"Private ","粉碎":"Shredding","自訂":"Customize ","分析":"Analyze ","新":"New ",
                          "變更":"Change ","位置查詢":"Location Query","總數":"Total","位元":"Bits","函數":"Func","本機":"Computer ",
                          "加密":"Encrypt ","解密":"Decrypt ","前":"Before","後":"After","文字":"Text","值":"Value ","密碼":"Password ",
                          "名":"Name","稱":"","類型":"Type","資料":"Data","日誌":"Log","返回":"Back","停止":"Stop ","  ":" "}}
