translations = {"zh_TW": {"已开启": "已開啟","已关闭": "已關閉","On": "已開啟","Off": "已關閉"},
                "zh_CN": {"On": "已开启","Off": "已关闭","已開啟": "已开启","已關閉": "已关闭",
                          "嗎": "吗","項": "项","復": "复","攔": "拦","請": "请","掃描": "扫描",
                          "鑰": "钥","統": "统","當": "当","確定": "确认","檔案": "文件",
                          "權限": "权限","惡意": "恶意","設定": "设置","後": "后","發現": "发现",
                          "關於": "关于","防護": "保护","軟體": "软件","引導扇區":"引导扇区",
                          "錯誤": "错误","實時": "实时"},
                "en_US": {"On":"On","Off":"Off","已开启":"On","已关闭":"Off","已開啟":"On","已關閉":"Off","嗎":"",
                          "存取被拒":"Access Denied ","病毒":"Virus ","個":"","選擇":"Select ","正在掃描":"Scanning ",
                          "正在刪除":"Deleting ","正在尋找":"Searching ","失敗":"Failed ","請":"Please ","方式":"Method ",
                          "當前":"Currently ","未":"Not ","防護":"Protect ","裝置":"Device ","這部":"This ","發現":"Found ",
                          "找到":"Find ","受到":"Been ","錯誤":"Error ","修復":"Repair ","完成":"Complete ","已":"Has ",
                          "正在初始化中":"Initializing ","實時":"Real-Time ","到":"For ","您確定":"Are You Sure ",
                          "系統":"System ","啟用":"Enable ","停用":"Disable ","重啟":"Reboot ","刪除":"Delete ","檔案":"File ",
                          "成功":"Success ","清理":"Cleanup ","執行":"Execute ","警告":"Warning ","輸入了":"Input ",
                          "搜尋":"Search ","此":"This ","要":"Want To ","安全模式":"Safe Boot Mode","您":"You ","的":"",
                          "命令":"Command","不是有效":"Is Not A Valid ","修改":"Modify ","用戶密碼":"User Password ",
                          "重置":"Reset ","網路":"Network ","配置":"Config ","是":"Is ","選項":"Options ","監控":"Monitor ",
                          "進程":"Process ","可以":"Can ","中":"","清除":"Delete ","並":"And ","密鑰":"Key ","攔截":"Block ",
                          "創建":"Create ","日期":"Date ","引導扇區":"Boot Sector ","掃描":"Scan ","設定":"Setting","關於":"About",}}
