translations = {"zh_TW": {"已开启": "已開啟","已关闭": "已關閉","On": "已開啟","Off": "已關閉"},
                "zh_CN": {"On": "已开启","Off": "已关闭","已開啟": "已开启","已關閉": "已关闭",
                          "嗎": "吗","項": "项","復": "复","攔": "拦","請": "请","掃描": "扫描",
                          "鑰": "钥","統": "统","當": "当","確定": "确认","檔案": "文件",
                          "權限": "权限","惡意": "恶意","設定": "设置","後": "后","發現": "发现",
                          "關於": "关于","防護": "保护","軟體": "软件","引導扇區":"引导扇区",
                          "錯誤": "错误","實時": "实时"},
                "en_US": {"Off":"Off","提示":"Tips","存取被拒":"Access denied","添加數據庫":"Add database",
                          "個病毒":" Virus","正在掃描: ":"Scanning: ","掃描失敗。":"Scan failed.","已关闭":"Off","On":"On",
                          "病毒掃描":"Virus scan","正在刪除: ":"Deleting: ","請選擇掃描方式":"Please select a scan method",
                          "正在初始化中，請稍後...":"Initializing, please wait...","當前未發現惡意軟體。":"No malware currently found.",
                          "這部裝置已受到保護":"This device has been protected","錯誤":"Error", "錯誤: ":"Error: ",
                          "這部裝置目前不安全":"This device is currently unsafe","修復完成!":"Repair complete!",
                          "當前已發現惡意軟體共{}項。":"A total of {} items of malware have been found so far.",
                          "安全密鑰錯誤":"Security Key Error","完成":"Finish","修復系統檔案":"Repair System Files",
                          "尚未啟用實時防護":"Real-time Protect is not enabled","修復失敗":"Repair failed",
                          "請輸入需要尋找的檔案":"Please enter the file you want to find","清理失敗":"Cleanup failed",
                          "成功: 已執行成功。":"Success: Executed successfully.","錯誤: 執行失敗。":"Error: Execution failed.",
                          "您確定要修復系統權限嗎?":"Are you sure you want to fix system permissions?",
                          "您確定要修復系統檔案嗎?":"Are you sure you want to repair the system files?",
                          "清理系統檔案":"Clean up system files","清理完成":"Cleanup complete","刪除檔案":"Delete file",
                          "您確定要清理系統檔案嗎?":"Are you sure you want to clean the system files?",
                          "啟用安全模式":"Enable safe mode","啟用失敗":"Enable failed","禁用安全模式":"Disable safe mode",
                          "您確定啟用安全模式嗎?":"Are you sure you enable safe mode?","禁用失敗":"Disable failed",
                          "使用該選項後需要重啟，現在要重啟嗎?":"A reboot is required after using this option, do you want to reboot now?",
                          "您確定禁用安全模式嗎?":"Are you sure you want to disable Safe Mode?","刪除失敗":"Failed to delete",
                          "您確定刪除該檔案嗎?":"Are you sure you want to delete this file?","刪除成功":"Success to deleted",
                          "運行成功":"Run successfully","不是有效命令":"Not a valid command","警告":"Warning",
                          "您輸入了錯誤的HEKY":"You entered the wrong HEKY","分析文件函數":"Analyze File Func",
                          "您輸入了錯誤的TYPE":"You entered the wrong TYPE","分析文件哈希值":"Analyze File Hashes",
                          "您確定要新增值或是修改值嗎?":"Are you sure you want to add or modify a value?",
                          "成功的創建或修改註冊表值":"Successfully created or modified registry value",
                          "分析文件位元":"Analyze File Bits","尋找結果:":"Find result:","正在尋找: ":"Searching: ",
                          "找到檔案: ":"File found: ","未找到檔案":"File Not Found","創建日期: ":"Created Date: ",
                          "您確定要修改用戶密碼嗎?":"Are you sure you want to change the user password?",
                          "IP查詢":"IP query","您的ip地址為:{}":"Your ip address is: {}","設定":"Setting",
                          "您確定要重置網路配置嗎?":"Are you sure you want to reset the network configuration?",
                          "重置網路配置成功":"Reset network configuration successful","關於":"About",
                          "結束進程":"End process","成功攔截惡意軟體: ":"Malware blocking success: ",
                          "啟用該選項可以實時監控進程中的惡意軟體並清除。":"Enable this option to monitor and remove malware in the system in real time.",
                          "啟用該選項可以提高掃描靈敏度，但這也可能會造成誤殺。":"Enable this option can improve scanning sensitivity, but it can also cause manslaughter.",
                          "成功修復註冊表: ":"Repair registry success: ","修復系統權限":"Repair System Permissions",
                          "成功修復引導扇區: PhysicalDrive0":"Repair boot sector success: PhysicalDrive0",
                          "正在掃描檔案安全性: ":"Scanning file security: ","惡意軟體攔截失敗: ":"Malware blocking failed: ",    
                          "實時防護已開啟":"Real-time protection is enabled","已開啟":"On", "已關閉":"Off","已开启":"On",}}
