english_list = {
"提示":"Tips",
"已開啟":"On",
"已關閉":"Off",
"已开启":"On",
"已关闭":"Off",
"正在刪除: ":"Deleting: ",
"正在删除":"Deleting: ",
"存取被拒":"Access denied",
" > [提示] 尚未啟用實時防護":" > [Tips] Real-time Protect is not enabled",
" > [提示] 尚未启用实时防护":" > [Tips] Real-time Protect is not enabled",
" > [行為防護] 成功攔截了惡意檔案創建行為。":" > [Behavior Protection] Successfully blocked malicious file creation behavior.",
" 被移動":" Moved",
" 被創建":" Created",
" 被刪除":" Deleted",
" 被編輯":" Edited",
"請輸入需要尋找的檔案":"Please enter the file you want to find",
"请输入需要寻找的档案":"Please enter the file you want to find",
"✔成功: 已執行成功。":"✔Success: Executed successfully.",
"這部裝置已受到保護":"This device has been protected",
"✖錯誤: 執行失敗。":"✖Error: Execution failed.",
" > [病毒掃描] 掃描出":" > [Virus Scan] scan out ",
"個病毒":" Virus",
"這部裝置目前不安全":"This device is currently unsafe",
"✖當前已發現惡意軟體共{}項。":"✖A total of {} items of malware have been found so far.",
'✔當前未發現惡意軟體。':'✔ No malware currently found.',
'正在掃描: ':'Scanning: ',
"病毒掃描":"Virus scan",
"正在初始化中，請稍後...":"Initializing, please wait...",
"✖當前已發現惡意軟體。":"✖Malware has currently been detected.",
"✖掃描失敗。":"✖Scan failed.",
"請選擇掃描方式":"Please select a scan method",
"您確定要修復系統權限嗎?":"Are you sure you want to fix system permissions?",
"修復完成!":"Repair complete!",
"完成":'Finish',
"您確定要修復系統檔案嗎?":"Are you sure you want to repair the system files?",
"修復系統檔案":'Repair System Files',
"錯誤":"Error",
"錯誤: ":"Error: ",
"[錯誤] ":"[Error] ",
"修復失敗":"Repair failed",
'清理系統檔案':'Clean up system files',
"您確定要清理系統檔案嗎?":"Are you sure you want to clean the system files?",
"清理完成":"Cleanup complete",
"清理失敗":"Cleanup failed",
"啟用安全模式":"Enable safe mode",
"您確定啟用安全模式嗎?":"Are you sure you enable safe mode?",
"使用該選項後需要重啟，現在要重啟嗎?":"A reboot is required after using this option, do you want to reboot now?",
"啟用失敗":"Enable failed",
'禁用安全模式':'Disable safe mode',
"您確定禁用安全模式嗎?":"Are you sure you want to disable Safe Mode?",
"禁用失敗":"Disable failed",
"刪除檔案":"Delete file",
"您確定刪除該檔案嗎?":"Are you sure you want to delete this file?",
"刪除成功":"Success to deleted",
"刪除失敗":"Failed to delete",
"運行成功":"Run successfully",
"不是有效命令":"Not a valid command",
"您輸入了錯誤的HEKY":"You entered the wrong HEKY",
"警告":"Warning",
"成功的創建或修改註冊表值":"Successfully created or modified registry value",
"分析文件函數":"Analyze File Func",
"分析文件哈希值":"Analyze File Hashes",
"分析文件位元":"Analyze File Bits",
'尋找結果:':'Find result:',
'正在尋找: ':'Searching: ',
'找到檔案:':'File found:',
'創建日期:':'Created Date:',
"您確定要修改用戶密碼嗎?":"Are you sure you want to change the user password?",
"IP查詢":"IP query",
"您的ip地址為:{}":"Your ip address is: {}",
"您確定要重置網路配置嗎?":"Are you sure you want to reset the network configuration?",
"重置網路配置成功":"Reset network configuration successful",
"設定":"Setting",
"關於":"About",
"結束進程":"End process",
"啟用該選項可以實時監控進程中的惡意軟體並清除。":"Enable this option to monitor and remove malware in the system in real time.",
"启用该选项可以实时监控进程中的恶意软件并清除。":"Enable this option to monitor and remove malware in the system in real time.",
"啟用該選項可以提高掃描靈敏度，但這也可能會造成誤殺。":"Enable this option can improve scanning sensitivity, but it can also cause manslaughter.",
"启用该选项可以提高扫描灵敏度，但这也可能会造成误杀。":"Enable this option can improve scanning sensitivity, but it can also cause manslaughter.",
'{} > [實時防護] 成功攔截了一個惡意軟體:':'{} > [Real-Time Protect] Malware blocking success:',
'{} > [實時防護] 惡意軟體攔截失敗:':'{} > [Real-Time Protect] Malware blocking failed:',
'修復系統權限':"Repair System Permissions",
'啟用該選項可以實時監控系統的檔案讀寫變更行為。':"Enable this option can improve scanning sensitivity, but it can also cause manslaughter.",
'PYAS':"""PYAS Python Antivirus Software Security
========================================
PYAS Create Date: 2020/12/17
Official Github: https://github.com/87owo/PYAS
Official Website: https://pyantivirus.wixsite.com/pyas
PYAS Core Developer: 87owo
PYAS GUI Developer: mtkiao
PYAS Data Collector: yang5487
PYAS Testers: 87owo, mtkiao
Special Thanks: Wix, Avast, Github, Google, Python,
Microsoft, VirusTotal, VirusShare, LenStevens
========================================
Thanks For Using PYAS Python Antivirus Software
"""}
